name: ublue bootc 40
on:
  pull_request:
  merge_group:
  schedule:
    - cron: '5 15 * * *'  # 3pm-ish UTC everyday (timed against official fedora container pushes)
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yaml
    secrets: inherit
    with:
      fedora_version: 40
