name: ublue bootc 41
on:
  pull_request:
  merge_group:
  schedule:
    - cron: '0 15 * * *'  # 3pm-ish UTC everyday (timed against official fedora container pushes)
  workflow_dispatch:

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yaml
    secrets: inherit
    with:
      fedora_version: 41
